spring:
  jwt:
    secretKey: vmfhwprxm

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      format_sql: true
      ddl-auto: create

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://myboard-database2.cs4usf0xv8ru.ap-northeast-2.rds.amazonaws.com:3306/myboard_db
    url: jdbc:mysql://localhost:3306/board_db?serverTimezone=Asia/Seoul&charaterEncoding=UTF-8
    username: root
    password: DDolchu0410!

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 510126896636-njlsscvepmc3bt5tv7prta6i4o1361ei.apps.googleusercontent.com
            client-secret: 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
#            redirect-uri: http://3.35.106.187/login/oauth2/code/google
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
          kakao:
            client-id: 6c59b4dda916bc7b5a99d658afc58a07
            client-secret:
#            redirect-uri: http://3.35.106.187/login/oauth2/code/kakao
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
              - profile_image
            client-name: kakao

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
  #  mail:
  #    host: smtp.gmail.com
  #    port: 587
  #    username:
  #    password:
  #    properties:
  #      mail:
  #        smtp:
  #          starttls:
  #            enable: true
  #            required: true
  #          auth: true
  #          connectiontimeout: 5000
  #          timeout: 5000
  #          writetimeout: 5000

  redis:
    host: 0.0.0.0
    port: 6379

  #  oauth2
  #  social:
  #    kakao:
  #      client_id: 6c59b4dda916bc7b5a99d658afc58a07
  #      redirect: http://localhost:8080/login/oauth2/code/kakao
  ##      redirect: http://localhost:8080/login/oauth2/code/kakao
  #      url:
  #        login: https://kauth.kakao.com/oauth/authorize
  #        token: https://kauth.kakao.com/oauth/token
  #        profile: https://kapi.kakao.com/v2/user/me
  #
  #    google:
  #      client_id: 510126896636-njlsscvepmc3bt5tv7prta6i4o1361ei.apps.googleusercontent.com
  #      client_secret: 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
  #      redirect: http://localhost:8080/login/oauth2/code/google
  #      url:
  #        login: https://accounts.google.com/o/oauth2/v2/auth
  #        token: https://oauth2.googleapis.com/token
  #        profile: https://www.googleapis.com/oauth2/v3/userinfo
  #
  #    naver:
  #      client_id:
  #      client_secret:
  #      redirect: http://localhost:8080/social/login/naver
  #      url:
  #        login: https://nid.naver.com/oauth2.0/authorize
  #        token: https://nid.naver.com/oauth2.0/token
  #        profile: https://openapi.naver.com/v1/nid/me

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 20MB
cloud:
  aws:
    credentials:
      accessKey: AKIA3VOBZPTXKQN34CS3
      secretKey: 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
    s3:
      bucket: potluck-test
    region:
      static: ap-northeast-2
    stack:
      auto: false

app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    #액세스토큰 유효기간 24시간
    tokenExpirationMsec: 86400000 
  cors:
    allowedOriginPatterns: http://localhost:3000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/auth/profil
#      - http://localhost:8080/auth/redirect/hi
#      - myandroidapp://oauth2/redirect
#      - myiosapp://oauth2/redirect